export const FETCH_ALL_CONTACTS = 'FETCH_ALL_CONTACTS'
export const FETCH_CONTACTS_SUCCESS = 'FETCH_CONTACTS_SUCCESS'
export const FETCH_CONTACTS_ERROR = 'FETCH_CONTACTS_ERROR'
export const REQUEST_CONTACTS = 'REQUEST_CONTACTS'

export const EDIT_CONTACT = 'EDIT_CONTACT'
export const SAVE_CONTACT = 'SAVE_CONTACT'
export const REMOVE_CONTACT = 'REMOVE_CONTACT'
